# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MVVMRXSwiftDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MVVMRXSwiftDemo
   pod 'RxSwift'
    pod 'RxCocoa'

  target 'MVVMRXSwiftDemoTests' do
    inherit! :search_paths
    # Pods for testing
     pod 'RxSwift'
    pod 'RxCocoa'
  end

  target 'MVVMRXSwiftDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
